### ISSUE TITLE
Bug: Providers not deleting dead files

### ISSUE THREAD

**Issue by TheMarstonConnell** [JackalLabs/canine-provider#53]
Providers are not removing files from the disk that they lose to downtime. #52 attempts to address this, which seems inefficient but works right now to mitigate the issue.

**Comment by TheMarstonConnell** [comment]
#63 attempts again to address this by rebuilding trees when it only half-deletes a file. Before this, it would have false positives and fail over and over again.

**Comment by dahn510** [comment]
#151 fixes this issue
